-- liquibase formatter sql

-- changeset andrewZ:1
CREATE TABLE IF NOT EXISTS links
(
    id         int GENERATED BY DEFAULT AS IDENTITY,
    short_link varchar NOT NULL UNIQUE,
    long_link  varchar NOT NULL UNIQUE,
    date       date,
    PRIMARY KEY (id, short_link, long_link)
)
-- rollback DROP TABLE links;
